CREATE OR REPLACE VIEW SNO_SANDBOX.IPL.STATUS_RECONCILIATION_BEDROCK_V AS
SELECT P.NAME AS PROGRAM_NAME
     , P.ID AS PROGRAM_ID
     , PL.NAME AS PROGRAM_LOAN_NAME
     , PL.ID AS PROGRAM_LOAN_ID
     , R.LAST_UPDATED_T AS ABOVE_UPDATED_TS
     , R.CURRENT_STATUS AS CURRENT_STATUS_ABOVE
     , PL.LOAN_APPLICATION_STATUS_C AS CURRENT_STATUS_BEYOND
     , PL.LENDER_STATUS_UPDATED_DATE_TIME_C_CST AS STATUS_RESPONSE_DATE_BEYOND
     , R.APP_SUBMIT_DATE AS APP_SUBMIT_DATE_ABOVE
     , R.OFFER_SELECTED_DATE
     , R.LOAN_START_DATE
     , R.INITIAL_LOAN_AMOUNT
     , R.AMOUNT_DISBURSED
     , NULL AS UPDATED_LOAN_STATUS_LEGACY
     , CASE
           WHEN CURRENT_STATUS_ABOVE IN ('BASIC_INFO_COMPLETE') THEN 'Basic info complete'
           WHEN CURRENT_STATUS_ABOVE IN ('ADD_INFO_COMPLETE') THEN 'Add info complete'
           WHEN CURRENT_STATUS_ABOVE IN ('FRONT_END_DECLINED', 'NO_OFFERS') THEN 'Front end declined'
           WHEN CURRENT_STATUS_ABOVE IN
                ('OFFERED', 'OFFERED_ALL', 'OFFERED_ALTERNATIVE_ONLY', 'OFFERED_EVEN_WITH_ALTERNATIVE')
               THEN 'Offered'
           WHEN CURRENT_STATUS_ABOVE IN ('OFFERED_SELECTED', 'ALTERNATIVE_SELECTED', 'EVEN_SELECTED')
               THEN 'Offer selected'
           WHEN CURRENT_STATUS_ABOVE IN ('EXPIRED') THEN 'Expired'
           WHEN CURRENT_STATUS_ABOVE IN ('WITHDRAWN')
               THEN 'Expired' --Temporary until withdrawn status built into Bedrock
           WHEN CURRENT_STATUS_ABOVE IN ('PENDING') THEN 'Pending'
           WHEN CURRENT_STATUS_ABOVE IN ('BACK_END_DECLINED') THEN 'Back end declined'
           WHEN CURRENT_STATUS_ABOVE IN ('APPROVED') THEN 'Approved'
           WHEN CURRENT_STATUS_ABOVE IN ('INITIAL_TIL_SUBMIT') THEN 'Initial TIL Submit'
           WHEN CURRENT_STATUS_ABOVE IN ('ONBOARDED') THEN 'Onboarded'
           WHEN CURRENT_STATUS_ABOVE IN ('BANK_SUBMIT') THEN 'Bank submit' -- Don't think there is a bank submit status
           END AS LOAN_STATUS_BEDROCK
     , CASE
           WHEN R.CURRENT_STATUS IN
                ('BASIC_INFO_COMPLETE', 'ADD_INFO_COMPLETE', 'OFFERED', 'OFFERED_ALL', 'OFFERED_ALTERNATIVE_ONLY',
                 'OFFERED_EVEN_WITH_ALTERNATIVE', 'OFFERED_SELECTED', 'PENDING', 'ALTERNATIVE_SELECTED',
                 'EVEN_SELECTED') THEN 'Application Submitted'
           WHEN R.CURRENT_STATUS IN ('FRONT_END_DECLINED', 'BACK_END_DECLINED', 'NO_OFFERS') THEN 'Decline'
           WHEN R.CURRENT_STATUS IN ('EXPIRED') THEN 'Expired'
           WHEN R.CURRENT_STATUS IN ('WITHDRAWN') THEN 'Expired' --Temporary until withdrawn status built into Bedrock
           WHEN R.CURRENT_STATUS IN ('INITIAL_TIL_SUBMIT', 'APPROVED', 'ONBOARDED') AND
                PL.LOAN_APPLICATION_STATUS_C NOT IN ('Funded', 'Graduated') THEN 'Approved'
           ELSE PL.LOAN_APPLICATION_STATUS_C
           END AS LOAN_APPLICATION_STATUS_BEDROCK
     , 'BEDROCK' AS SOURCE_SYSTEM
     , CURRENT_DATE AS LOADED_DATE
     , NULL AS ELIGIBLE_FOR_LUSA_CURRENT
     , NULL AS LOAN_SUB_STATUS_CURRENT
     , R.ORIG_FEE
     , R.DECLINE_REASON_1 AS DECLINE_REASON
FROM REFINED_PROD.BEDROCK.PROGRAM_C AS P
     LEFT JOIN (
               SELECT *
               FROM REFINED_PROD.BEDROCK.PROGRAM_LOAN_C
               WHERE NOT IS_DELETED
                   QUALIFY RANK()
                                   OVER (PARTITION BY PROGRAM_ID_C ORDER BY CREATED_DATE_CST DESC, NAME DESC) =
                           1
               ) PL ON PL.PROGRAM_ID_C = P.ID
     JOIN (
          SELECT *
          FROM SNO_SANDBOX.IPL.IPL_RETURN_FILE
              QUALIFY rank()
                              OVER (PARTITION BY PROGRAM_ID ORDER BY LOADED_DATE DESC, coalesce(APP_SUBMIT_DATE, '1901-01-01'), DECLINE_REASON_1 DESC) =
                      1
          ) R ON P.NAME = R.PROGRAM_ID AND R.LOADED_DATE = CURRENT_DATE
WHERE TRUE;

