CREATE OR REPLACE VIEW SNO_SANDBOX.IPL.STATUS_RECONCILIATION_LEGACY_V AS
SELECT P.NAME AS PROGRAM_NAME
     , P.ID AS PROGRAM_ID
     , NULL AS PROGRAM_LOAN_NAME
     , NULL AS PROGRAM_LOAN_ID
     , R.LAST_UPDATED_T AS ABOVE_UPDATED_TS
     , R.CURRENT_STATUS AS CURRENT_STATUS_ABOVE
     , P.LOAN_INTEREST_STATUS_C AS CURRENT_STATUS_BEYOND
     , P.LOAN_INTEREST_RESPONSE_DATE_C_CST AS STATUS_RESPONSE_DATE_BEYOND
     , R.APP_SUBMIT_DATE AS APP_SUBMIT_DATE_ABOVE
     , R.OFFER_SELECTED_DATE
     , R.LOAN_START_DATE
     , R.INITIAL_LOAN_AMOUNT
     , R.AMOUNT_DISBURSED
     , CASE -- add a date check on the most recent loan status change vs the Above fields
--            WHEN P.ELIGIBLE_FOR_LUSA_C AND CURRENT_STATUS_BEYOND NOT IN ('Funded', 'Graduated', 'Final (Pre-Qualified)',
--                                                                         'Pre-Qualified: Pending Estimate',
--                                                                         'Preapproved') THEN NULL
           WHEN CURRENT_STATUS_BEYOND IN ('Funded', 'Graduated', 'Not Interested') THEN CURRENT_STATUS_BEYOND
           WHEN CURRENT_STATUS_ABOVE IN ('FRONT_END_DECLINED', 'BACK_END_DECLINED') THEN 'UW Declined'
           WHEN CURRENT_STATUS_BEYOND = 'Interested - Skybridge' THEN 'Above - Loan In progress'
           WHEN CURRENT_STATUS_ABOVE IN ('EXPIRED') THEN NULL
           WHEN CURRENT_STATUS_ABOVE IN ('WITHDRAWN') THEN NULL
           WHEN CURRENT_STATUS_ABOVE IN
                ('BASIC_INFO_COMPLETE', 'ADD_INFO_COMPLETE', 'OFFERED', 'OFFERED_SELECTED', 'PENDING', 'APPROVED',
                 'INITIAL_TIL_SUBMIT') THEN 'Above - Loan In progress'
           WHEN CURRENT_STATUS_ABOVE IN ('ONBOARDED') AND CURRENT_STATUS_BEYOND NOT IN ('Funded', 'Graduated')
               THEN 'Above - Loan In progress'
           ELSE CURRENT_STATUS_BEYOND
           END AS UPDATED_LOAN_STATUS_LEGACY
     , NULL AS LOAN_STATUS_BEDROCK
     , NULL AS LOAN_APPLICATION_STATUS_BEDROCK
     , 'LEGACY' AS SOURCE_SYSTEM
     , CURRENT_DATE AS LOADED_DATE
     , P.ELIGIBLE_FOR_LUSA_C AS ELIGIBLE_FOR_LUSA_CURRENT
     , P.LOAN_SUB_STATUS_C AS LOAN_SUB_STATUS_CURRENT
     , R.ORIG_FEE
     , R.DECLINE_REASON_1 AS DECLINE_REASON
FROM REFINED_PROD.SALESFORCE.NU_DSE_PROGRAM_C AS P
     JOIN (
          SELECT *
          FROM SNO_SANDBOX.IPL.IPL_RETURN_FILE
              QUALIFY rank() OVER (PARTITION BY PROGRAM_ID
                                  ORDER BY LOADED_DATE DESC, coalesce(APP_SUBMIT_DATE, '1901-01-01') DESC, LAST_UPDATED_T DESC, DECLINE_REASON_1 DESC) =
                      1
          ) R ON P.NAME = R.PROGRAM_ID AND R.LOADED_DATE = CURRENT_DATE
WHERE CURRENT_STATUS_BEYOND IS DISTINCT FROM UPDATED_LOAN_STATUS_LEGACY;

